name: My Test Single Project
on:
    push:
    pull_request:

jobs:
    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest
        steps:
        -   name: Check out the Git repository
            uses: actions/checkout@v4
            with:
                fetch-depth: 0 
        -   name: Set up Java toolchain
            uses: actions/setup-java@v4
            with:
                distribution: "temurin"
                java-version: "21"
                cache: "gradle"
        -   name: Set gradlew as executable
            run: chmod +x ./gradlew
        -   name: SonarCloud Scan
            uses: SonarSource/sonarcloud-github-action@master
            env: 
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
                SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}